version: '3'

services:
  client:
    build:
      context: client
      dockerfile: ./Dockerfile
    ports:
      - 8081:80
    depends_on: 
      - server
  server:
    build:
      context: server
      dockerfile: ./Dockerfile
    ports:
      - 8080:80
