version: '3'

services:
  client:
    build:
      context: client
      dockerfile: ./Dockerfile
      args:
        API_URL: ${SERVER_URL:-http://localhost:8080}
    ports:
      - ${CLIENT_PORT:-8081}:80
    depends_on: 
      - server
  server:
    build:
      context: server
      dockerfile: ./Dockerfile
    ports:
      - ${SERVER_PORT:-8080}:80
    environment:
      - ALLOWED_ORIGIN=${CLIENT_URL:-http://localhost:8081}
      - MONGO_URI=mongodb://database:27017
    depends_on:
      - database
  database:
    image: mongo:4.4.0
    ports:
      - 27017:27017
