version: '3'

services: 
  game:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 80:80
    depends_on: 
      - eventstore
  eventstore:
    image: eventstore/eventstore
    ports:
      - 2113:2113
      - 1113:1113
