apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    game: armadora
    tier: client
    app: client
spec:
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      # TODO: missing container specs (CPU / RAM)
      containers:
      - name: client
        image: thomasferro/armadora-client:0.0.1
        ports:
        - containerPort: 80
