apiVersion: v1
kind: Service
metadata:
  name: eventstore
spec:
  selector:
    app: eventstore
  ports:
    - name: "2113"
      protocol: TCP
      port: 2113
    - name: "1113"
      protocol: TCP
      port: 1113
