apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  labels:
    game: armadora
    tier: server
    app: server
spec:
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      # TODO: missing container specs (CPU / RAM)
      containers:
      - name: server
        image: thomasferro/armadora-server:0.0.1
        ports:
        - containerPort: 80
        env:
        - name: ALLOWED_ORIGIN
        # TODO: value based on ingress ?
          value: http://localhost:8080
