apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  labels:
    game: armadora
    tier: server
    app: server
spec:
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: thomasferro/armadora-server:0.0.1
        ports:
        - containerPort: 80
