apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    game: armadora
    tier: server
    app: server
spec:
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: thomasferro/armadora-server:0.0.1
        ports:
        - containerPort: 80
        env:
        - name: ALLOWED_ORIGIN
        # TODO: value based on ingress ?
          value: https://play.armadora.test
        # TODO: Health check ?
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"

---

apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 80
  type: NodePort

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: server-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: api.armadora.test
    http:
      paths:
      - path: /
        backend:
          serviceName: server
          servicePort: 80
